### ISSUE TITLE
When having inheritance in class under test adding class in @PrepareForTest and running the test gives initilizationError

### ISSUE THREAD

**Issue by shailuJD** [jayway/powermock#583] opened 2015-10-08 15:28 UTC
I am trying to run test for last couple of days not much help provided on web search as well.

I am using below JARS

cglib-nodep-2.2.2.jar
javassist-3.20.0-GA.jar
junit-4.12.jar
mockito-all-1.10.19.jar
objenesis-2.1.jar
powermock-mockito-1.6.3-full.jar

Stack trace is below :-

java.lang.ClassFormatError: JVMCFRE013 local variable PC length invalid; class=<ParentClass>, offset=18919
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:284)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:221)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:268)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:179)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:70)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:658)
	at java.lang.ClassLoader.defineClassImpl(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:284)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:221)
	at org.powermock.core.classloader.MockClassLoader.loadMockClass(MockClassLoader.java:268)
	at org.powermock.core.classloader.MockClassLoader.loadModifiedClass(MockClassLoader.java:179)
	at org.powermock.core.classloader.DeferSupportingClassLoader.loadClass(DeferSupportingClassLoader.java:70)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:658)
	at java.lang.Class.forNameImpl(Native Method)
	at java.lang.Class.forName(Class.java:176)
	at sun.reflect.generics.factory.CoreReflectionFactory.makeNamedType(CoreReflectionFactory.java:126)
	at sun.reflect.generics.visitor.Reifier.visitClassTypeSignature(Reifier.java:137)
	at sun.reflect.generics.tree.ClassTypeSignature.accept(ClassTypeSignature.java:61)
	at sun.reflect.annotation.AnnotationParser.parseSig(AnnotationParser.java:402)
	at sun.reflect.annotation.AnnotationParser.parseClassValue(AnnotationParser.java:383)
	at sun.reflect.annotation.AnnotationParser.parseClassArray(AnnotationParser.java:685)
	at sun.reflect.annotation.AnnotationParser.parseArray(AnnotationParser.java:492)
	at sun.reflect.annotation.AnnotationParser.parseMemberValue(AnnotationParser.java:318)
	at sun.reflect.annotation.AnnotationParser.parseAnnotation(AnnotationParser.java:253)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations2(AnnotationParser.java:100)
	at sun.reflect.annotation.AnnotationParser.parseAnnotations(AnnotationParser.java:82)
	at java.lang.Class.getDeclaredAnnotations(Class.java:1685)
	at java.lang.Class.getAnnotations(Class.java:1641)
	at java.lang.Class.getAnnotation(Class.java:1621)
	at org.junit.internal.MethodSorter.getDeclaredMethods(MethodSorter.java:52)
	at org.junit.internal.runners.TestClass.getAnnotatedMethods(TestClass.java:45)
	at org.junit.internal.runners.MethodValidator.validateTestMethods(MethodValidator.java:71)
	at org.junit.internal.runners.MethodValidator.validateStaticMethods(MethodValidator.java:44)
	at org.junit.internal.runners.MethodValidator.validateMethodsForDefaultRunner(MethodValidator.java:50)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.validate(PowerMockJUnit44RunnerDelegateImpl.java:108)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit44RunnerDelegateImpl.<init>(PowerMockJUnit44RunnerDelegateImpl.java:70)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit47RunnerDelegateImpl.<init>(PowerMockJUnit47RunnerDelegateImpl.java:42)
	at org.powermock.modules.junit4.internal.impl.PowerMockJUnit49RunnerDelegateImpl.<init>(PowerMockJUnit49RunnerDelegateImpl.java:25)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:156)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.createDelegatorFromClassloader(JUnit4TestSuiteChunkerImpl.java:40)
	at org.powermock.tests.utils.impl.AbstractTestSuiteChunkerImpl.createTestDelegators(AbstractTestSuiteChunkerImpl.java:244)
	at org.powermock.modules.junit4.common.internal.impl.JUnit4TestSuiteChunkerImpl.<init>(JUnit4TestSuiteChunkerImpl.java:61)
	at org.powermock.modules.junit4.common.internal.impl.AbstractCommonPowerMockRunner.<init>(AbstractCommonPowerMockRunner.java:32)
	at org.powermock.modules.junit4.PowerMockRunner.<init>(PowerMockRunner.java:34)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:80)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:57)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:539)
	at org.junit.internal.builders.AnnotatedBuilder.buildRunner(AnnotatedBuilder.java:104)
	at org.junit.internal.builders.AnnotatedBuilder.runnerForClass(AnnotatedBuilder.java:86)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.builders.AllDefaultPossibilitiesBuilder.runnerForClass(AllDefaultPossibilitiesBuilder.java:26)
	at org.junit.runners.model.RunnerBuilder.safeRunnerForClass(RunnerBuilder.java:59)
	at org.junit.internal.requests.ClassRequest.getRunner(ClassRequest.java:33)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.<init>(JUnit4TestReference.java:32)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestClassReference.<init>(JUnit4TestClassReference.java:25)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.createTest(JUnit4TestLoader.java:41)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestLoader.loadTests(JUnit4TestLoader.java:31)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:452)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:683)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:390)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:197)

**Comment by johanhaleby** [comment] 2015-10-08 17:41
Could you try upgrading to the latest version and see if it's still an issue?

**Comment by shailuJD** [comment] 2015-10-09 05:47
I am using the latest version only downloaded from below link

https://github.com/jayway/powermock/wiki/Downloads

**Comment by johanhaleby** [comment] 2015-10-09 06:22
Oh sorry. Did you experience the same problem in a previous version?

**Comment by shailuJD** [comment] 2015-10-09 07:07
I have tried with version 1.6.2 same problem.

I tried writing simple test case this time different error. The code is follows

public class TestA{
	private int a;
	public int getA() {
		return a;
	}
	public void setA(int a) {
		this.a = a;
	}
}

public class TestB extends TestA{
	private int b;
	public TestB() {
		super();
	}
	public int getB() {
		return b;
	}
	public void setB(int b) {
		this.b = b;
	}
	public void test(){
		
	}
}

import org.junit.Test;
import org.junit.runner.RunWith;
import org.mockito.Spy;
import org.powermock.core.classloader.annotations.PrepareForTest;
import org.powermock.modules.junit4.PowerMockRunner;

@RunWith(PowerMockRunner.class)
@PrepareForTest(value = {TestB.class})
public class TestBTest {
	@Spy
	TestB b = new TestB();
	
	@Test
	public void test_test(){
		b.test();
	}
}


As soon as I remove extends A in Class TestB every thing is fin.

**Comment by johanhaleby** [comment] 2015-10-09 09:14
To me this sound like a byte-code problem. Byte-code is handled by javassist so I think that you should report it as a bug there.

**Comment by shailuJD** [comment] 2015-10-09 09:59
I have raised issue with Javaassist below the link 

https://issues.jboss.org/projects/JASSIST/issues/JASSIST-252

**Comment by johanhaleby** [comment] 2015-10-09 10:56
Thanks!

**Comment by thekingnothing** [comment] 2016-04-10 05:51
Close the issue as cannot be reproduced. I cannot reproduce the issue with using latest JDK, javassist and PowerMock 
-  JDK 1.8.77 for MacOS
-  JDK 1.7.79 for MacOS
-  org.javassist:javassist:jar:3.20.0-GA:compile
-  PowerMock 1.6.5-SNAPSHOT

**Closed by thekingnothing** 2016-04-10 05:51 UTC
Labels: bug, Priority:High, Status:cannot reproduce
